### ISSUE TITLE
How do I remove a datamonitor

### ISSUE THREAD

**Issue by Mike-Honey** [isdapro/Slack-Kaggle-Bot#1]
I set up a datamonitor on an insanely busy dataset - how can I remove it from my list?

Its:
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge

Thanks!

**Comment by isdapro** [comment]
Hey Mike, the v2 of the app is up now. You can now use the stop command to stop monitoring any dataset. There are some other features that have been added too!

**Comment by Mike-Honey** [comment]
:party-parrot: !

Thanks so much - I'll give it a try.  Very timely as I have a few new ones to monitor, and I saw you added functionality there also.
